services:
  postgres-service:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - default

  rabbitmq-service:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default

  database-sevice:
    build: ./database-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres-service
      RMQ_DATABASE_QUEUE: ${RMQ_DATABASE_QUEUE}
      RMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq-service:5672
    depends_on:
      - postgres-service
      - rabbitmq-service
    networks:
      - default

  #auth-service:
   # build: ./auth-service
    #environment:
     # RMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq-service:5672
     # RMQ_AUTH_QUEUE: ${RMQ_AUTH_QUEUE}
      #RMQ_DATABASE_QUEUE: ${RMQ_DATABASE_QUEUE}
    #depends_on:
     # - database-sevice
    #networks:
     # - default

networks: 
  default:
    driver: bridge