services:
  postgres-service:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - default
  rabbitmq-service:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
    networks:
      - default
  database-sevice:
    build: ./database-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: database
      RMQ_DATABASE_QUEUE: ${RMQ_DATABASE_QUEUE}
      RMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      - database
    networks:
      - default
  comanda-service:
    build: ./comanda-service
    environment:
      RMQ_COMANDA_QUEUE: ${RMQ_COMANDA_QUEUE}
      RMQ_DATABASE_QUEUE: ${RMQ_DATABASE_QUEUE}
      RMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      - rabbitmq
      - database-sevice
    networks:
      - default
networks: 
  default:
    driver: bridge